export enum ErrorCodes {
  // NOT FOUND
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_REVIEWED = 'USER_ALREADY_REVIEWED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // CONFLICT
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // BAD REQUEST
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // UNAUTHORIZED
  INVALID_TOKEN = 'INVALID_TOKEN',
  INCORRECT_LOGIN_CREDENTIALS = 'INCORRECT_LOGIN_CREDENTIALS',

  // SERVER ERROR
  SERVER_ERROR = 'SERVER_ERROR',
}
